# Generated by Django 6.0.6 on 2026-06-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentlog_duration_at_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='origin_office',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
